version: '3.3'
services:
  oracledb:
    image: oracle-database
    ports:
      - '1521:1521'
    environment:
      ORACLE_SID: 'ORCLCDB'
      ORACLE_PDB: 'ORCLPDB1' #database name
      ORACLE_PWD: 'ORCLPDB1'
      # INIT_SGA_SIZE:
      # INIT_PGA_SIZE:
      # INIT_CPU_COUNT:
      # INIT_PROCESSES:
      ORACLE_EDITION: 'standard'
      ORACLE_CHARACTERSET: 'AL32UTF8'
      # ENABLE_ARCHIVELOG:false
      ENABLE_TCPS: 'true'
    volumes:
      - data:/opt/oracle/oradata
volumes:
  data: